create table if not exists users (
    user_id bigint generated by default as identity primary key,
    username varchar(100) not null,
    pc_name varchar(100) not null,
    user_group varchar(100),
    phone_number varchar(15),
    cabinet varchar(15),
    discription text,
    birthdate date,
    created_at TIMESTAMP not null default current_timestamp, 
    modified_at TIMESTAMP

);
