FROM golang:alpine AS builder
WORKDIR /go/src/app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -mod vendor -o /go/src/app/out

FROM scratch
COPY --from=builder /go/src/app/out /app/main/main
WORKDIR /app/main
ENTRYPOINT ["./main"]